version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: weekly
      day: sunday
      time: '00:00'
    open-pull-requests-limit: 10

  - package-ecosystem: npm
    directory: /infra/cloudflare
    schedule:
      interval: weekly
      day: sunday
      time: '00:00'
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: sunday
      time: '00:00'
    open-pull-requests-limit: 5
